#!/bin/bash

set -e

pushd "$(dirname $0)" > /dev/null

git add .

if ! git diff --quiet HEAD; then
    git remote add upstream "${bamboo_planRepository_repositoryUrl}"
    git -c user.name="Maintenance Bot" -c user.email="team-magazin@chefkoch.de" commit -a -F  /build/commit.txt
    git push upstream "${bamboo_planRepository_branchName}"
fi
