#!/bin/bash

set -e

pushd "$(dirname $0)" > /dev/null

git add .

if ! git diff --quiet HEAD; then
    git commit -a -F  build/commit.txt
    git push upstream "${bamboo_planRepository_branchName}"
fi
